name: 'northwind_dbt'
version: '1.0.0'
profile: 'northwind_dbt'

# Configurações dos diretórios
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

# Configurações dos modelos
models:
  northwind_dbt:
    bronze:
      +schema: 'bronze'
    silver:
      +schema: 'silver'
    gold:
      +schema: 'gold'