name: Update MKDocs

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocstrings

      - name: Deploy GitHub Pages
        run: mkdocs gh-deploy --force --clean --verbose
